sudo: false
language: node_js
node_js: 
  - 12.11.0
before_script:
  - npm install
script:
  - npm run test:unit
notifications:
  email: false
before_install:
  - npm i -g npm@6.9.0  
after_success:
  - ./bin/codecov -e TRAVIS_NODE_VERSION -f coverage/*.json